name: Test

on:
  push:

jobs:
  integration:
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_DB: bookshelf_test
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: bookshelf_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -ppass"
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Configure MySQL
        run: |
          mysql -e "ALTER USER 'root'@'localhost' \
          IDENTIFIED WITH mysql_native_password BY 'root';"
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
      - run: npm ci
      - run: npm test
